### ISSUE TITLE
Call to undefined method ParamProcessor\Processor::setParameterDefinitions()

### ISSUE THREAD

**Issue by vgangt** [ProfessionalWiki/Maps#750]
Hello, we have MW 1.39.4 LTS version in our RHEL 7 server. We have installed number of extensions and most of them are working properly. But Maps doesn't. Tried to add this one to show map, {{#display_map:center=Berlin|width=400|height=250}}

It throws below error:
/wiki/index.php?title=Testmap&action=submit Error: Call to undefined method ParamProcessor\Processor::setParameterDefinitions()

Backtrace:

from /data/www/html/wiki/extensions/Maps/src/Map/DisplayMap/DisplayMapFunction.php(58)
#0 /data/www/html/wiki/extensions/Maps/src/ParserHookSetup.php(80): Maps\Map\DisplayMap\DisplayMapFunction->getMapHtmlForKeyValueStrings()
#1 /data/www/html/wiki/extensions/Maps/src/ParserHookSetup.php(58): Maps\ParserHookSetup->handleFunctionHook()
#2 /data/www/html/wiki/includes/parser/Parser.php(3437): Maps\ParserHookSetup->Maps\{closure}()
#3 /data/www/html/wiki/includes/parser/Parser.php(3122): Parser->callParserFunction()
#4 /data/www/html/wiki/includes/parser/PPFrame_Hash.php(275): Parser->braceSubstitution()
#5 /data/www/html/wiki/includes/parser/Parser.php(2951): PPFrame_Hash->expand()
#6 /data/www/html/wiki/includes/parser/Parser.php(1609): Parser->replaceVariables()
#7 /data/www/html/wiki/includes/parser/Parser.php(723): Parser->internalParse()
#8 /data/www/html/wiki/includes/content/WikitextContentHandler.php(301): Parser->parse()
#9 /data/www/html/wiki/includes/content/ContentHandler.php(1721): WikitextContentHandler->fillParserOutput()
#10 /data/www/html/wiki/includes/content/Renderer/ContentRenderer.php(47): ContentHandler->getParserOutput()
#11 /data/www/html/wiki/includes/EditPage.php(4534): MediaWiki\Content\Renderer\ContentRenderer->getParserOutput()
#12 /data/www/html/wiki/includes/EditPage.php(4437): EditPage->doPreviewParse()
#13 /data/www/html/wiki/includes/EditPage.php(3143): EditPage->getPreviewText()
#14 /data/www/html/wiki/includes/EditPage.php(778): EditPage->showEditForm()
#15 /data/www/html/wiki/includes/actions/EditAction.php(73): EditPage->edit()
#16 /data/www/html/wiki/includes/actions/SubmitAction.php(38): EditAction->show()
#17 /data/www/html/wiki/includes/MediaWiki.php(542): SubmitAction->show()
#18 /data/www/html/wiki/includes/MediaWiki.php(322): MediaWiki->performAction()
#19 /data/www/html/wiki/includes/MediaWiki.php(904): MediaWiki->performRequest()
#20 /data/www/html/wiki/includes/MediaWiki.php(562): MediaWiki->main()
#21 /data/www/html/wiki/index.php(50): MediaWiki->run()
#22 /data/www/html/wiki/index.php(46): wfIndexMain()
#23 {main} 

Product	Version
[MediaWiki]	1.39.4
[PHP]	8.0.25 (apache2handler)
[MySQL]	8.0.26

Semantic MediaWiki | 4.1.1 | 
Maps | 10.0.0 | 

I am not sure why its throwing this error since all the required extensions and libs are installed (as per my knowledge). anybody knows why this behavior?

Thanks in advance...
Vishnu

**Comment by malberts** [comment]
ParamProcessor is part of a Composer dependency and should've been downloaded when running composer update. How did you install Maps?

**Comment by vgangt** [comment]
Hi,
I added these two lines in require section of composer.json and run composer update no-dev (as suggested in the extension doc)
"mediawiki/semantic-media-wiki": "4.1.1",
"mediawiki/maps": "^10.0"
Then added, below lines in Localsettings.php and after that, executed update.php script
wfLoadExtension( 'SemanticMediaWiki');
wfLoadExtension( 'Maps' );

I think the paramprocessor got installed automatically as dependency. ..

--
Vishnu.

**Comment by vgangt** [comment]
Hi,
I cloned the paramprocessor codes (https://github.com/JeroenDeDauw/ParamProcessor.git) manually to the extension folder
 and added in LocalSettings.php,
require_once( "$IP/extensions/ParamProcessor/src/Processor.php" );
require_once( "$IP/extensions/ParamProcessor/src/ParamDefinitionFactory.php" );

Now this error is gone atleast... But still the map is not loading properly, it just showing in middle of Atlantic Sea. :) 
--
Vishnu
