### ISSUE TITLE
GeoJson expected value of type array or object, null given

### ISSUE THREAD

**Issue by redheadkelly** [ProfessionalWiki/Maps#768]
I'm getting the error '/mediawiki-1.39.5/index.php?title=GeoJson:ApplecrossMonastery&action=submit GeoJson\Exception\UnserializationException: GeoJson expected value of type array or object, null given'

I'm running:
MediaWiki   1.39.5
PHP   7.4.33 (apache2handler)
MariaDB  10.4.27-MariaDB
Lua  5.1.5
Maps  10.1.0

on xampp on Windows 10.

I know there was a previous issue that required changing a 'if ( $this->parserOutput !== null )' statement, so I tried that. It didn't help.

This is the full error...

Thanks.

[600b8651a67905feb5ffab68] /mediawiki-1.39.5/index.php?title=GeoJson:ApplecrossMonastery&action=submit GeoJson\Exception\UnserializationException: GeoJson expected value of type array or object, null given

Backtrace:

from C:\xampp\htdocs\mediawiki-1.39.5\vendor\jmikola\geojson\src\Exception\UnserializationException.php(24)
#0 C:\xampp\htdocs\mediawiki-1.39.5\vendor\jmikola\geojson\src\GeoJson.php(77): GeoJson\Exception\UnserializationException::invalidValue(string, NULL, string)
#1 C:\xampp\htdocs\mediawiki-1.39.5\extensions\Maps\src\GeoJsonPages\Semantic\SubObjectBuilder.php(21): GeoJson\GeoJson::jsonUnserialize(NULL)
#2 C:\xampp\htdocs\mediawiki-1.39.5\extensions\Maps\src\GeoJsonPages\Semantic\SemanticGeoJsonStore.php(29): Maps\GeoJsonPages\Semantic\SubObjectBuilder->getSubObjectsFromGeoJson(string)
#3 C:\xampp\htdocs\mediawiki-1.39.5\extensions\Maps\src\GeoJsonPages\GeoJsonContentHandler.php(49): Maps\GeoJsonPages\Semantic\SemanticGeoJsonStore->storeGeoJson(string)
#4 C:\xampp\htdocs\mediawiki-1.39.5\includes\content\ContentHandler.php(1721): Maps\GeoJsonPages\GeoJsonContentHandler->fillParserOutput(Maps\GeoJsonPages\GeoJsonContent, MediaWiki\Content\Renderer\ContentParseParams, ParserOutput)
#5 C:\xampp\htdocs\mediawiki-1.39.5\includes\content\Renderer\ContentRenderer.php(47): ContentHandler->getParserOutput(Maps\GeoJsonPages\GeoJsonContent, MediaWiki\Content\Renderer\ContentParseParams)
#6 C:\xampp\htdocs\mediawiki-1.39.5\includes\Revision\RenderedRevision.php(266): MediaWiki\Content\Renderer\ContentRenderer->getParserOutput(Maps\GeoJsonPages\GeoJsonContent, Title, integer, ParserOptions, boolean)
#7 C:\xampp\htdocs\mediawiki-1.39.5\includes\Revision\RenderedRevision.php(237): MediaWiki\Revision\RenderedRevision->getSlotParserOutputUncached(Maps\GeoJsonPages\GeoJsonContent, boolean)
#8 C:\xampp\htdocs\mediawiki-1.39.5\includes\Revision\RevisionRenderer.php(221): MediaWiki\Revision\RenderedRevision->getSlotParserOutput(string, array)
#9 C:\xampp\htdocs\mediawiki-1.39.5\includes\Revision\RevisionRenderer.php(158): MediaWiki\Revision\RevisionRenderer->combineSlotOutput(MediaWiki\Revision\RenderedRevision, array)
#10 [internal function]: MediaWiki\Revision\RevisionRenderer->MediaWiki\Revision\{closure}(MediaWiki\Revision\RenderedRevision, array)
#11 C:\xampp\htdocs\mediawiki-1.39.5\includes\Revision\RenderedRevision.php(199): call_user_func(Closure, MediaWiki\Revision\RenderedRevision, array)
#12 C:\xampp\htdocs\mediawiki-1.39.5\includes\Storage\DerivedPageDataUpdater.php(1438): MediaWiki\Revision\RenderedRevision->getRevisionParserOutput()
#13 [internal function]: MediaWiki\Storage\DerivedPageDataUpdater->getCanonicalParserOutput()
#14 C:\xampp\htdocs\mediawiki-1.39.5\includes\edit\PreparedEdit.php(97): call_user_func(array)
#15 C:\xampp\htdocs\mediawiki-1.39.5\extensions\SemanticMediaWiki\src\MediaWiki\EditInfo.php(102): MediaWiki\Edit\PreparedEdit->getOutput()
#16 C:\xampp\htdocs\mediawiki-1.39.5\extensions\SemanticMediaWiki\src\MediaWiki\Hooks\RevisionFromEditComplete.php(84): SMW\MediaWiki\EditInfo->fetchEditInfo()
#17 C:\xampp\htdocs\mediawiki-1.39.5\extensions\SemanticMediaWiki\src\MediaWiki\Hooks.php(620): SMW\MediaWiki\Hooks\RevisionFromEditComplete->process(Title)
#18 C:\xampp\htdocs\mediawiki-1.39.5\includes\HookContainer\HookContainer.php(338): SMW\MediaWiki\Hooks->onRevisionFromEditComplete(WikiPage, MediaWiki\Revision\RevisionStoreRecord, boolean, User, array)
#19 C:\xampp\htdocs\mediawiki-1.39.5\includes\HookContainer\HookContainer.php(137): MediaWiki\HookContainer\HookContainer->callLegacyHook(string, array, array, array)
#20 C:\xampp\htdocs\mediawiki-1.39.5\includes\HookContainer\HookRunner.php(3227): MediaWiki\HookContainer\HookContainer->run(string, array)
#21 C:\xampp\htdocs\mediawiki-1.39.5\includes\Storage\PageUpdater.php(1538): MediaWiki\HookContainer\HookRunner->onRevisionFromEditComplete(WikiPage, MediaWiki\Revision\RevisionStoreRecord, boolean, User, array)
#22 C:\xampp\htdocs\mediawiki-1.39.5\includes\Storage\PageUpdater.php(942): MediaWiki\Storage\PageUpdater->doCreate(CommentStoreComment)
#23 C:\xampp\htdocs\mediawiki-1.39.5\includes\EditPage.php(2597): MediaWiki\Storage\PageUpdater->saveRevision(CommentStoreComment, integer)
#24 C:\xampp\htdocs\mediawiki-1.39.5\includes\EditPage.php(1905): EditPage->internalAttemptSave(array, boolean, boolean)
#25 C:\xampp\htdocs\mediawiki-1.39.5\includes\EditPage.php(722): EditPage->attemptSave(array)
#26 C:\xampp\htdocs\mediawiki-1.39.5\includes\actions\EditAction.php(73): EditPage->edit()
#27 C:\xampp\htdocs\mediawiki-1.39.5\includes\actions\SubmitAction.php(38): EditAction->show()
#28 C:\xampp\htdocs\mediawiki-1.39.5\includes\MediaWiki.php(542): SubmitAction->show()
#29 C:\xampp\htdocs\mediawiki-1.39.5\includes\MediaWiki.php(322): MediaWiki->performAction(Article, Title)
#30 C:\xampp\htdocs\mediawiki-1.39.5\includes\MediaWiki.php(904): MediaWiki->performRequest()
#31 C:\xampp\htdocs\mediawiki-1.39.5\includes\MediaWiki.php(562): MediaWiki->main()
#32 C:\xampp\htdocs\mediawiki-1.39.5\index.php(50): MediaWiki->run()
#33 C:\xampp\htdocs\mediawiki-1.39.5\index.php(46): wfIndexMain()
#34 {main}Product	Version
[MediaWiki](https://www.mediawiki.org/)	1.39.5
[PHP](https://php.net/)	7.4.33 (apache2handler)
[MariaDB](https://mariadb.org/)	10.4.27-MariaDB
[ICU](https://icu.unicode.org/)	66.1
[Lua](http://www.lua.org/)	5.1.5[Maps](https://maps.extension.wiki/)	10.1.0

**Comment by JeroenDeDauw** [comment]
Try get latest version, has GeoJSON fix https://github.com/ProfessionalWiki/Maps/blob/master/RELEASE-NOTES.md

**Comment by JeroenDeDauw** [comment]
Please reopen if present on master

**Comment by redheadkelly** [comment]
Upgraded to 10.1.1 and got new error on 1.39.5. So I upgraded to 1.39.6 and got the same error.

MediaWiki	1.39.6
PHP	7.4.33 (apache2handler)
MariaDB	10.4.27-MariaDB
Lua	5.1.5
Maps	10.1.1
Semantic MediaWiki	4.1.3

[32fd9786046ed34a7f1a4122] /mediawiki-1.39.6/index.php/GeoJson:ArdclachParish ParseError: syntax error, unexpected ')', expecting '|' or variable (T_VARIABLE)

Backtrace:

from C:\xampp\htdocs\mediawiki-1.39.6\extensions\Maps\src\GeoJsonPages\Semantic\SubObjectBuilder.php(25)
#0 [internal function]: AutoLoader::autoload(string)
#1 C:\xampp\htdocs\mediawiki-1.39.6\extensions\Maps\src\MapsFactory.php(243): spl_autoload_call(string)
#2 C:\xampp\htdocs\mediawiki-1.39.6\extensions\Maps\src\GeoJsonPages\GeoJsonContentHandler.php(50): Maps\MapsFactory->newSemanticGeoJsonStore(ParserOutput, Title)
#3 C:\xampp\htdocs\mediawiki-1.39.6\includes\content\ContentHandler.php(1721): Maps\GeoJsonPages\GeoJsonContentHandler->fillParserOutput(Maps\GeoJsonPages\GeoJsonContent, MediaWiki\Content\Renderer\ContentParseParams, ParserOutput)
#4 C:\xampp\htdocs\mediawiki-1.39.6\includes\content\Renderer\ContentRenderer.php(47): ContentHandler->getParserOutput(Maps\GeoJsonPages\GeoJsonContent, MediaWiki\Content\Renderer\ContentParseParams)
#5 C:\xampp\htdocs\mediawiki-1.39.6\includes\Revision\RenderedRevision.php(266): MediaWiki\Content\Renderer\ContentRenderer->getParserOutput(Maps\GeoJsonPages\GeoJsonContent, Title, integer, ParserOptions, boolean)
#6 C:\xampp\htdocs\mediawiki-1.39.6\includes\Revision\RenderedRevision.php(237): MediaWiki\Revision\RenderedRevision->getSlotParserOutputUncached(Maps\GeoJsonPages\GeoJsonContent, boolean)
#7 C:\xampp\htdocs\mediawiki-1.39.6\includes\Revision\RevisionRenderer.php(221): MediaWiki\Revision\RenderedRevision->getSlotParserOutput(string, array)
#8 C:\xampp\htdocs\mediawiki-1.39.6\includes\Revision\RevisionRenderer.php(158): MediaWiki\Revision\RevisionRenderer->combineSlotOutput(MediaWiki\Revision\RenderedRevision, array)
#9 [internal function]: MediaWiki\Revision\RevisionRenderer->MediaWiki\Revision\{closure}(MediaWiki\Revision\RenderedRevision, array)
#10 C:\xampp\htdocs\mediawiki-1.39.6\includes\Revision\RenderedRevision.php(199): call_user_func(Closure, MediaWiki\Revision\RenderedRevision, array)
#11 C:\xampp\htdocs\mediawiki-1.39.6\includes\poolcounter\PoolWorkArticleView.php(91): MediaWiki\Revision\RenderedRevision->getRevisionParserOutput()
#12 C:\xampp\htdocs\mediawiki-1.39.6\includes\poolcounter\PoolWorkArticleView.php(72): PoolWorkArticleView->renderRevision()
#13 C:\xampp\htdocs\mediawiki-1.39.6\includes\poolcounter\PoolCounterWork.php(162): PoolWorkArticleView->doWork()
#14 C:\xampp\htdocs\mediawiki-1.39.6\includes\page\ParserOutputAccess.php(299): PoolCounterWork->execute()
#15 C:\xampp\htdocs\mediawiki-1.39.6\includes\page\Article.php(714): MediaWiki\Page\ParserOutputAccess->getParserOutput(WikiPage, ParserOptions, MediaWiki\Revision\RevisionStoreRecord, integer)
#16 C:\xampp\htdocs\mediawiki-1.39.6\includes\page\Article.php(528): Article->generateContentOutput(User, ParserOptions, integer, OutputPage, array)
#17 C:\xampp\htdocs\mediawiki-1.39.6\includes\actions\ViewAction.php(78): Article->view()
#18 C:\xampp\htdocs\mediawiki-1.39.6\includes\MediaWiki.php(542): ViewAction->show()
#19 C:\xampp\htdocs\mediawiki-1.39.6\includes\MediaWiki.php(322): MediaWiki->performAction(Article, Title)
#20 C:\xampp\htdocs\mediawiki-1.39.6\includes\MediaWiki.php(904): MediaWiki->performRequest()
#21 C:\xampp\htdocs\mediawiki-1.39.6\includes\MediaWiki.php(562): MediaWiki->main()
#22 C:\xampp\htdocs\mediawiki-1.39.6\index.php(50): MediaWiki->run()
#23 C:\xampp\htdocs\mediawiki-1.39.6\index.php(46): wfIndexMain()
#24 {main}

**Comment by JeroenDeDauw** [comment]
That is a different error, but one that indicates why you are running into problems.

**Comment by JeroenDeDauw** [comment]
This was fixed by https://github.com/ProfessionalWiki/Maps/pull/764

**Comment by JeroenDeDauw** [comment]
This is part of the newly released Maps 10.1.2

**Comment by redheadkelly** [comment]
Thanks Jeroen. Appreciate it.

This is what I'm getting now....

https://www.rosssurnameproject.net/wiki/index.php/GeoJson:ApplecrossParish

MediaWiki	1.39.6
PHP	8.2.15 (litespeed)
MySQL	5.7.23-23
Maps	10.1.2
Semantic MediaWiki	4.1.3

Not sure what to make of this. Don't know if this is something I'm not doing right or if this is the extension. Although, I know these files have actually rendered as maps previously. Same thing is happening on my local xampp install.

Also, sorry. Apparently, I don't know how to 'reopen' something.

**Comment by JeroenDeDauw** [comment]
Only maintainers can reopen issues

It's also bad practice to reuse an issue for different things

You are now seemingly running into what this PR is attempting to fix: https://github.com/ProfessionalWiki/Maps/pull/767
